dist: trusty
sudo: required
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
after_success:
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh
notifications:
  email: false